# Generated by Django 4.1.1 on 2022-09-26 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='行业名')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '行业',
                'verbose_name_plural': '行业',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='城市名')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='公司描述')),
                ('degree', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F')], max_length=5, null=True, verbose_name='ESG评分等级')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('tag', models.CharField(blank=True, max_length=10, null=True, verbose_name='公司标签')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='公司详情')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='公司地址')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m', verbose_name='封面图')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='行业')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.city', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='Company_S_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('file', models.FileField(max_length=200, upload_to='course/resourse/%Y/%m', verbose_name='下载地址')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': '公司S资源',
                'verbose_name_plural': '公司S资源',
            },
        ),
        migrations.CreateModel(
            name='Company_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('value', models.IntegerField(default='0', verbose_name='资产')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='公司')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='行业')),
            ],
            options={
                'verbose_name': '公司社会信息',
                'verbose_name_plural': '公司社会信息',
            },
        ),
        migrations.CreateModel(
            name='Company_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('file', models.FileField(max_length=200, upload_to='course/resourse/%Y/%m', verbose_name='下载地址')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '公司资源',
                'verbose_name_plural': '公司资源',
            },
        ),
        migrations.CreateModel(
            name='Company_G_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('file', models.FileField(max_length=200, upload_to='course/resourse/%Y/%m', verbose_name='下载地址')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': '公司G资源',
                'verbose_name_plural': '公司G资源',
            },
        ),
        migrations.CreateModel(
            name='Company_G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('value', models.IntegerField(default='0', verbose_name='资产')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='公司')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='行业')),
            ],
            options={
                'verbose_name': '公司管理信息',
                'verbose_name_plural': '公司管理信息',
            },
        ),
        migrations.CreateModel(
            name='Company_E_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('file', models.FileField(max_length=200, upload_to='course/resourse/%Y/%m', verbose_name='下载地址')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': '公司E资源',
                'verbose_name_plural': '公司E资源',
            },
        ),
        migrations.CreateModel(
            name='Company_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('value', models.IntegerField(default='0', verbose_name='资产')),
                ('Greenhouse_gas_emissions', models.IntegerField(default='0', verbose_name='温室气体排放量')),
                ('Discharge_value_of_hazardous_waste', models.IntegerField(default='0', verbose_name='有害废弃物排放量')),
                ('Discharge_value_of_harmless_waste', models.IntegerField(default='0', verbose_name='无害废弃物排放量')),
                ('Energy_consumption', models.IntegerField(default='0', verbose_name='能源消耗量')),
                ('water_consumption', models.IntegerField(default='0', verbose_name='耗水量')),
                ('Environmental_protection_action_investment', models.IntegerField(default='0', verbose_name='环境保护投资量')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='公司')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='行业')),
            ],
            options={
                'verbose_name': '公司环境信息',
                'verbose_name_plural': '公司环境信息',
            },
        ),
    ]
