# Generated by Django 4.1.1 on 2022-09-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_e',
            name='date',
            field=models.IntegerField(default='2022', max_length=4, verbose_name='信息年份'),
        ),
    ]
